const express = require('express')
const http = require('https')
const fs = require('fs')
const cookie = require('cookie-parser')
require('dotenv').config()
const multer = require('multer')
const storage =  multer.diskStorage({ destination: 'uploads/', filename: (req, file, reply) =>{ reply( null, Date.now()+'_'+file.originalname.replaceAll(' ','_') )    }})
const up = multer({ storage })
const app = express()
app.use(express.static('./viewers'))
app.use(cookie())
app.use( express.urlencoded({ extends: true }))
app.use(express.json())
require('./controllers/index')( app, up )
http.createServer({ key: fs.readFileSync('./key.pem'), cert: fs.readFileSync('./cert.pem')}, app ).listen( process.env.PORT || 3000,()=>console.log('running on point...'))
